name: Testing
language: python
os:
  - linux
  - osx
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install requests
  - flask run -d
  - sleep 5
  - python -m unittest
